services:
  backend:
    image: node:22.14-alpine
    working_dir: /app
    user: node
    ports:
      - "3001:3001"
    volumes:
      - ./backend:/app
    command: npm run start

  frontend:
    image: node:22.14-alpine
    working_dir: /app
    user: node
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/:/app
    command: npm run dev
